@echo off
echo Stopping containers...
docker compose down -v

echo Starting containers...
docker compose up -d

echo Waiting 5 seconds for DB to start...
timeout /t 5 >nul

echo Running tests...
pytest -v
